### PR TITLE
feat: support export artifacts with manifest mode

### LINKED ISSUE #45: Using export mode with vcpkg manifest mode
vcpkg works with the export artifacts now,see https://devblogs.microsoft.com/cppblog/vcpkg-2023-10-19-release-export-for-manifests-documentation-improvements-and-more/

Manually export routine with manifest configured dependencies:
```bash
    vcpkg install --triplet=x64-windows --host-triplet=x64-windows
    vcpkg export --raw --triplet=x64-windows --host-triplet=x64-windows --output=x64-windows --output-dir=export
```

### PR DESCRIPTION
**Pull request by msclock**
Close #45

### CODE REVIEW

**Comment by eclipse0922** [comment]
Hi, I came across this PR while looking up vcpkg export and install. 
Did you find that not only the export, but also the install works fine with this method?

**Comment by eclipse0922** [comment]
@msclock Thank you for the reply.

I will try as you described.

**Comment by msclock** [comment]
> @msclock Thank you for the reply.
> 
> I will try as you described.

@eclipse0922 I have add the install depends command ` vcpkg install --triplet=${VCPKG_TARGET_TRIPLET} --host-triplet=${VCPKG_TARGET_TRIPLET} `, and it  works with manifest mode configuration. That might be what you care about.

**Comment by eclipse0922** [comment]
@msclock I appreciate you

**Comment by msclock** [comment]
> @msclock I appreciate you

you're welcome😄 @eclipse0922

**Comment by msclock** [comment]
This feature implemented by #78, and it would be closed when #78 merged.

**Pull request closed without merging**
